apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-trading-bot
  template:
    metadata:
      labels:
        app: simple-trading-bot
    spec:
      containers:
      - name: simple-trading-bot
        image: simple-trading-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_REDIS_HOST
          value: redis
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: SPRING_KAFKA_PRODUCER_CLIENT_ID
          value: trading-bot-producer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: trading-bot
        - name: TRADING_KAFKA_TOPICS_TRADE_SIGNALS
          value: trading.signals
        - name: TRADING_KAFKA_TOPICS_TRADE_EXECUTION
          value: trading.executions
        - name: TRADING_KAFKA_TOPICS_RISK_EVENTS
          value: trading.risk
        - name: TRADING_KAFKA_TOPICS_MARKET_DATA
          value: trading.market-data
        - name: TRADING_KAFKA_TOPICS_BOT_STATUS
          value: trading.bot-status
        - name: exchange
          value: "binance" # or bybit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092
        - containerPort: 9101
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_JMX_HOSTNAME
          value: localhost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"