version: '3.8'

services:
  simple-trading-bot:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_CLIENT_ID=trading-bot-producer
      - SPRING_KAFKA_CONSUMER_GROUP_ID=trading-bot
      - TRADING_KAFKA_TOPICS_TRADE_SIGNALS=trading.signals
      - TRADING_KAFKA_TOPICS_TRADE_EXECUTION=trading.executions
      - TRADING_KAFKA_TOPICS_RISK_EVENTS=trading.risk
      - TRADING_KAFKA_TOPICS_MARKET_DATA=trading.market-data
      - TRADING_KAFKA_TOPICS_BOT_STATUS=trading.bot-status
      - exchange=binance # or bybit
    networks:
      - trading-network

  # Zookeeper - required for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: trading-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - trading-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: trading-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - trading-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge